### ISSUE TITLE
Update to reflect changes made to CyTube

### ISSUE THREAD

**Issue by calzoneman** [CyTube/cytube-docker#1]
Originally reported in https://github.com/calzoneman/sync/issues/774.

Several config.yaml changes have been made in the past year that are not reflected here (see https://github.com/calzoneman/sync/commits/3.0/config.template.yaml).

**Comment by Gelmo** [comment]
Got a fork going here:

https://github.com/Gelmo/cytube-docker

Having trouble building cytubefilters with and without the changes by @davidsiaw so I'll have to look further into pcre on Alpine tomorrow. I'm done for the day but if you want to try it out, the README is updated.

Edit: Made a separate branch for Ubuntu. Builds successfully as it should but I haven't tested running it. Heading to bed and I'll try during my break. Will also try Alpine from another base.

**Comment by Gelmo** [comment]
Ubuntu image builds and runs but not successfully. I'll debug that later. Has some pcre issues when building cytubefilters too, but ultimately passes. Build logs of alpine and ubuntu images here:

https://hub.docker.com/r/gelmo/cytube-docker/builds/bsbpnahzztcm6uad4pdbpw7/

https://hub.docker.com/r/gelmo/cytube-docker/builds/bigmgjpipmswckdzvtnuemk/

I'm working on the 3rd dockerfile now, with a different alpine base

**Comment by calzoneman** [comment]
Building on Alpine requires this patch: https://github.com/calzoneman/cytubefilters/commit/ffdbce83c6cf806f9ae0983cc735230fefcfdb5a

Which is present in https://github.com/CyTube/cytube-docker/blob/master/scripts/package.json but doesn't match the commit hash in CyTube's package.json.

**Comment by Gelmo** [comment]
@calzoneman You'll see in the non-ubuntu branches of my fork that I use sed to replace the commit to ffdbce8 - That is not the solution in this case

**Comment by Gelmo** [comment]
@calzoneman https://github.com/Gelmo/cytube-docker/commit/d9504ad74a995e7233334d18974dbc25e82d8c5b#diff-34b175266de56d56120e9576f71486c9

**Comment by calzoneman** [comment]
Ok, but the build log shows gcc erroring out on a missing definition for
`strtoq` and that commit on cytubefilters to fix the build on Alpine undefs
`HAVE_STRTOQ` so I'm wondering if what you're intending to patch is
actually what ends up getting built.

**Comment by Gelmo** [comment]
@calzoneman Yea, I've been looking into it and clearly I was making some mistakes in regard to execution order. Got a working one now and doing some tests.

**Comment by Gelmo** [comment]
@calzoneman Have any idea why it's pulling from #67c7c69a when further up in the logs it shows #ffdbce8 in the package.json? Very confused :(

```
"cytubefilters": "git://github.com/calzoneman/cytubefilters#ffdbce8"
```
```
[            ......] - extract:cytubefilters: sill extract cytubefilters@git://github.com/calzoneman/cytubefilters.git#67c7c69a extracted to /home/cytube/app/node_modules/.staging/cytubefilters-7c49d7d3 (4295ms)
```

**Comment by calzoneman** [comment]
https://github.com/Gelmo/cytube-docker/blob/a7ea4fead6f6002915cfc51ca9080fcb5b304fed/scripts/docker-entrypoint.sh#L185

> `sed 's/67c7c69a/ffdbce8/' package.json`

This will just print the replaced content to stdout.  You want `sed -i` to overwrite the file in-place.

>       -i[SUFFIX], --in-place[=SUFFIX]
>
>              edit files in place (makes backup if SUFFIX supplied)

**Comment by calzoneman** [comment]
Although a better solution would probably be to just fix the commit hash upstream :)

**Comment by Gelmo** [comment]
@calzoneman That worked, thank you :D I'm getting closer now.

The reason I'm replacing within package.json from Sync upstream rather than including a separate package.json is because I intend on eventually condensing this to 2-3 files and making a PR for Sync, rather than cytube-docker. The more files it utilizes from the head upstream the better

**Comment by Gelmo** [comment]
Latest version at my fork and at https://hub.docker.com/r/gelmo/cytube-docker/ works! Making a clean branch for a PR for cytube-docker now

**Comment by Gelmo** [comment]
Updated.
